# NumPy

In [3]:
import numpy as np

In [5]:
lista = np.array([[1,2],[3,4]])
lista[0][0]

1

In [7]:
lista[0,:]

array([1, 2])

In [8]:
lista.transpose()

array([[1, 3],
       [2, 4]])

In [10]:

l1 = np.array([[1,2],[3,4]])
l2 = np.array([[1,2],[3,4]])
l1+l2

array([[2, 4],
       [6, 8]])

In [15]:
l3 = np.arange(1,2000000)
l3.sum()

-1455759936

In [18]:
print(l3[2000:])

[   2001    2002    2003 ... 1999997 1999998 1999999]
